Declare default virtual destructors to quiet [-Wnon-virtual-dtor]
microsoft/wil pull request #405
Opened 2023-12-05 16:28 UTC by bashi-bazouk

This change allows compiling ComTests.cpp and ResourceTests.cpp with -Werror -Wnon-virtual-dtor enabled.

2023-12-05 16:36 UTC, dunhor commented
I get that these types are just for unit tests, but these are all COM types where the destructor really shouldn't be part of the v-table because the type destroys itself in the `Release` method. If these warnings are causing issue, we should disable them either globally or locally at their definitions

2023-12-10 02:27 UTC, ChrisGuzak approved these changes

2023-12-28 03:57 UTC, jonwis requested changes

2023-12-28 03:57 UTC, jonwis commented on tests/ComTests.cpp
> +   virtual ~ITest() = default;
This should be `~IDerivedTest` - you can't declare a destructor for a base type.

2023-12-28 03:57 UTC, jonwis commented on tests/ComTests.cpp
> +   virtual ~ITestInspectable() = default;
Same as above; s/b `~IDerivedTestInspectable`

2023-12-28 03:59 UTC, jonwis commented
In a earlier project, we kept finding leaks when someone had the pattern `class CIntermediate : IFooExtendsIUnknown` then `class CDerivedMost : CIntermediate` where the `CDerivedMost` overrode a method on `IFooExtendsIUnknown` and added additional state. The `delete this` in `CIntermediate::Release` didn't trigger `~CDerivedMost` because nobody had a `virtual ~Anything()` in the type hierarchy.  The super easy fix was to just add `virtual ~CIntermediate() { };` and all the leaks got closed.

So I'm sympathetic to the warning.  Should it be firing for types that contain only types with trivial destructors, though? Like the `FakeStream` type has no state to destroy and no members with nontrivial destructors.

So the two that need it in this change are the `IUnknownFake` (an instance with non-pure-virtual methods) and `FakeStream`. The others are just "pure interfaces."

2025-10-06 18:57 UTC, closed without merging